name: Verilator CI

on: [push, pull_request]

jobs:
  verilator-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Verilator
      run: |
        sudo apt-get update
        sudo apt-get install -y verilator make g++

    - name: Run Verilator Build
      run: |
        verilator -Wall --cc adder.sv --exe adder_tb.cpp --top-module adder
        make -C obj_dir -f Vadder.mk Vadder

    - name: Run Simulation
      run: ./obj_dir/Vadder

